\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{xjtuthesis_2014_pm}[2016/07/31 v1.0 LaTeX document class for Professional Master thesis of Xi'an Jiaotong University]
\DeclareOption*{\PassOptionsToClass{\CurrentOption}{xjtuthesis_2014}}
\ProcessOptions\relax
\LoadClass[cs4size,openany]{xjtuthesis_2014}
\setdegreetypestrchs{硕士}{Master}
\setthesistypestreng{thesis}
\setdisciplinelabelchs{类别（领域）}{Professional Fields}