\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{xjtuthesis_2014_pd}[2016/07/31 v1.0 LaTeX document class for Professional Ph. D. thesis of Xi'an Jiaotong University]
\DeclareOption*{\PassOptionsToClass{\CurrentOption}{xjtuthesis_2014}}
\ProcessOptions\relax
\LoadClass[cs4size,openany]{xjtuthesis_2014}
\setdegreetypestrchs{博士}{Doctor}
\setthesistypestreng{dissertation}
\setdisciplinelabelchs{类别（领域）}{Professional Fields}